server:
  port: 80
#默认端口号 访问时直接通过localhost访问
spring:
  application:
    name: consumer
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: /WEB-INF/html/
  resources:
    static-locations: classpath:static/

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
#    register-with-eureka: false
#    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true