server:
  port: 8001
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    jedis:
      pool:
        min-idle: 2
        max-idle: 10
        max-wait: -1
        max-active: 1000
    database: 0
  application:
    name: TransationServer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/bank?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhiling.bank.entity       #所有Entity别名类所在包

eureka:
  instance:
    hostname: localhost
    instance-id: Ta:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/
info:
  app:
    name: T
  author:
    name: Mr.
  server:
    port: ${server.port}

